/*
 * ListadosVentana.java
 *
 * Created on 24 de febrero de 2006, 11:00
 */

package interfazSGF;

/**
 *
 * @author  davidvalle
 */
class ListadosVentana extends javax.swing.JDialog {
    
    /** Creates new form ListadosVentana */
    public ListadosVentana(int tipo, int nFilas, String [] listado,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();                  
        
        javax.swing.JLabel [] labelTitulos=null;
         if(tipo<BufferDeRegistro.nombre_catalogos.length && tipo>0){
            labelTitulos=new javax.swing.JLabel [BufferDeRegistro.campos_catalogos[tipo].length];
            String titulo = BufferDeRegistro.nombre_catalogos[tipo];
            setTitle(titulo);
            String [] campos=BufferDeRegistro.campos_catalogos[tipo];
            for(int i=0;i<campos.length;i++){
                labelTitulos[i]=new javax.swing.JLabel(campos[i]+"\t\t");
            }
        }else{
            setTitle("Acceso invertido");
            labelTitulos = new javax.swing.JLabel[]{};
            jPTitulos.setVisible(false);
        }
        //Creamos la tabla:
         jPTitulos.setLayout(new java.awt.GridLayout(1, labelTitulos.length));          
         
         //Metemos t�tulos de la tabla:
         for(int i=0;i<labelTitulos.length;i++){
            labelTitulos[i].setFont(new java.awt.Font("Tahoma", 3, 11));
            javax.swing.JPanel panel =new javax.swing.JPanel();
            panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
            (panel).add(labelTitulos[i]);             
            (jPTitulos).add(labelTitulos[i]);            
         }
        //La rellenamos
        for (int i = 0; i < listado.length;i++){
             javax.swing.JTextArea jtarea = new javax.swing.JTextArea(listado[i]);             
             javax.swing.JPanel panel =new javax.swing.JPanel();
             panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));                          
             if(i!=0)jTPListado.setText(jTPListado.getText()+"\n"+listado[i]);
             else jTPListado.setText(listado[i]);
        }
        jLFilas.setText((new Integer(nFilas)).toString()); 
        getContentPane().add(jSPListado);
        pack();
        repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPResumen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLFilas = new javax.swing.JLabel();
        jPTitulos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSPListado = new javax.swing.JScrollPane();
        jTPListado = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado");
        setLocationByPlatform(true);
        jPResumen.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setText("N\u00famero de filas:");
        jPanel1.add(jLabel1);

        jLFilas.setText("0");
        jPanel1.add(jLFilas);

        jPResumen.add(jPanel1);

        getContentPane().add(jPResumen, java.awt.BorderLayout.SOUTH);

        jPTitulos.setLayout(new java.awt.GridLayout(1, 0));

        getContentPane().add(jPTitulos, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(14, 0));
        jSPListado.setAutoscrolls(true);
        jTPListado.setEditable(false);
        jSPListado.setViewportView(jTPListado);

        jPanel2.add(jSPListado);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String [] s=new String[200];
                for(int i=0;i<s.length;i++)s[i]=(new Integer(i)).toString();
                new ListadosVentana(1,s.length-1,s,new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLFilas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPResumen;
    private javax.swing.JPanel jPTitulos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jSPListado;
    private javax.swing.JTextPane jTPListado;
    // End of variables declaration//GEN-END:variables
    
}
