//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoCliente.DominoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DominoServiceReference.IDominoService", CallbackContract=typeof(DominoCliente.DominoServiceReference.IDominoServiceCallback))]
    public interface IDominoService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/RequestSitPlayer")]
        void RequestSitPlayer(string PlayerName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/RequestSitPlayer")]
        System.Threading.Tasks.Task RequestSitPlayerAsync(string PlayerName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/RequestPutPiecePlayer")]
        void RequestPutPiecePlayer(DominoService.PieceData piece, DominoService.PieceData prevPiece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/RequestPutPiecePlayer")]
        System.Threading.Tasks.Task RequestPutPiecePlayerAsync(DominoService.PieceData piece, DominoService.PieceData prevPiece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/PasoElTurno")]
        void PasoElTurno(int quienPasa);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/PasoElTurno")]
        System.Threading.Tasks.Task PasoElTurnoAsync(int quienPasa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDominoServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/NewPlayerJoined")]
        void NewPlayerJoined(DominoService.PlayerData player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/PuttedPiece")]
        void PuttedPiece(DominoService.PieceData piece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/PlayerNotSat")]
        void PlayerNotSat(string ErrorMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/ShowPiece")]
        void ShowPiece(DominoService.PieceData piece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/ActualizarMarcadores")]
        void ActualizarMarcadores(int[] Marcadores);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/LimpiarCliente")]
        void LimpiarCliente();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/ShowPieceUpdate")]
        void ShowPieceUpdate(DominoService.PieceData piece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/PutPiece")]
        void PutPiece(DominoService.PieceData piece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/NewPutPieceOnPanel")]
        void NewPutPieceOnPanel(DominoService.PieceData piece);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDominoService/ElTurnoEsDe")]
        void ElTurnoEsDe(int posicionJugadorConTurno, bool puedePoner, int puedo1, int puedo2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDominoServiceChannel : DominoCliente.DominoServiceReference.IDominoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DominoServiceClient : System.ServiceModel.DuplexClientBase<DominoCliente.DominoServiceReference.IDominoService>, DominoCliente.DominoServiceReference.IDominoService {
        
        public DominoServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DominoServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DominoServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DominoServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DominoServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RequestSitPlayer(string PlayerName) {
            base.Channel.RequestSitPlayer(PlayerName);
        }
        
        public System.Threading.Tasks.Task RequestSitPlayerAsync(string PlayerName) {
            return base.Channel.RequestSitPlayerAsync(PlayerName);
        }
        
        public void RequestPutPiecePlayer(DominoService.PieceData piece, DominoService.PieceData prevPiece) {
            base.Channel.RequestPutPiecePlayer(piece, prevPiece);
        }
        
        public System.Threading.Tasks.Task RequestPutPiecePlayerAsync(DominoService.PieceData piece, DominoService.PieceData prevPiece) {
            return base.Channel.RequestPutPiecePlayerAsync(piece, prevPiece);
        }
        
        public void PasoElTurno(int quienPasa) {
            base.Channel.PasoElTurno(quienPasa);
        }
        
        public System.Threading.Tasks.Task PasoElTurnoAsync(int quienPasa) {
            return base.Channel.PasoElTurnoAsync(quienPasa);
        }
    }
}
